name = "ai-todo-assistant"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Production D1 Database
[[d1_databases]]
binding = "DB"
database_name = "ai-todo-db"
database_id = "9abb1bc1-f8ed-4a1b-b68a-bc6735cf65d3"

# Production KV Namespace
[[kv_namespaces]]
binding = "AUTH_KV"
id = "c8c7f95847234890a13a0c82cef14696"

# R2 Storage for images
[[r2_buckets]]
binding = "IMAGE_STORAGE"
bucket_name = "ai-todo-images"

# Environment variables for OpenRouter AI
[vars]
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
# Text model for regular parsing
TEXT_MODEL_NAME = "deepseek/deepseek-r1-0528:free"
# Multi-modal model for image recognition  
MULTI_MODEL_NAME = "google/gemini-2.0-flash-exp:free"
NODE_ENV = "production"

# These should be set as secrets via wrangler secret put
# OPENROUTER_API_KEY = "your-openrouter-api-key-here" 